"""Render docs/DATA.md from the pipeline outputs.

Every number in the document is read from the tokenized meta.json and from the
tokenizer file itself, so the prose cannot drift away from the corpus that was
built. Rerun this after any rerun of 04_tokenize.py.

The web extension written by scripts/13_filter_ext.py is covered as well. Its
per-shard token counts are derived from the shard files when they are present on
this machine and cached in analysis/corpus_extension.json, which is committed so
that the document renders identically on a machine holding no bulk data. Paths
that name the bulk root are rendered through portable_path so the document does
not carry one machine's home directory.
"""

from __future__ import annotations

import json
from pathlib import Path

from small_lm_lab.paths import TOKENIZED_ROOT, portable_path

REPO_ROOT = Path(__file__).resolve().parents[1]
META_PATH = TOKENIZED_ROOT / "meta.json"
DOC_PATH = REPO_ROOT / "docs" / "DATA.md"
EXT_RECORD_PATH = REPO_ROOT / "analysis" / "corpus_extension.json"
EXT_SHARD_GLOB = "fineweb_edu_train_ext_*.bin"
# Token ids are stored as unsigned 16 bit integers, so a shard's token count is
# exactly half its byte length.
BYTES_PER_TOKEN = 2

DOMAIN_TITLES = {"tinystories": "TinyStories", "fineweb_edu": "FineWeb-Edu"}


def derive_extension_record() -> dict | None:
    """Per-shard extension token counts, read from the shards on this machine."""
    shards = sorted(TOKENIZED_ROOT.glob(EXT_SHARD_GLOB))
    if not shards:
        return None
    files = [
        {"file": p.name, "bytes": p.stat().st_size, "tokens": p.stat().st_size // BYTES_PER_TOKEN}
        for p in shards
    ]
    return {
        "domain": "fineweb_edu",
        "split": "train",
        "produced_by": "scripts/13_filter_ext.py",
        "shards": files,
        "tokens": sum(f["tokens"] for f in files),
    }


def load_extension_record() -> dict | None:
    """The extension record, refreshed from disk when the shards are present."""
    derived = derive_extension_record()
    if derived is not None:
        EXT_RECORD_PATH.parent.mkdir(parents=True, exist_ok=True)
        with EXT_RECORD_PATH.open("w") as f:
            json.dump(derived, f, indent=2)
            f.write("\n")
        return derived
    if EXT_RECORD_PATH.exists():
        with EXT_RECORD_PATH.open() as f:
            return json.load(f)
    return None


def fmt(n: int) -> str:
    return f"{n:,}"


def millions(n: int) -> str:
    return f"{n / 1e6:.1f}M"


def bin_size(domain: str, split: str) -> str:
    """Human readable size, scaled so the small holdout files stay legible."""
    path = TOKENIZED_ROOT / f"{domain}_{split}.bin"
    if not path.exists():
        return "missing"
    size = path.stat().st_size
    return f"{size/1e9:.2f} GB" if size >= 1e9 else f"{size/1e6:.1f} MB"


def render(meta: dict, ext: dict | None = None) -> str:
    domains = meta["domains"]
    tok = meta["tokenizer"]
    proto = meta["split_protocol"]

    ts = domains["tinystories"]
    fw = domains["fineweb_edu"]
    ts_prov = ts["provenance"]
    fw_prov = fw["provenance"]

    def total_tokens(m: dict) -> int:
        return sum(m["tokens"].values())

    grand_total = sum(total_tokens(m) for m in domains.values())
    train_total = sum(m["tokens"]["train"] for m in domains.values())
    ts_share = 100.0 * total_tokens(ts) / grand_total
    fw_share = 100.0 * total_tokens(fw) / grand_total

    lines: list[str] = []
    add = lines.append

    add("# Data")
    add("")
    add(
        "Two open corpora with verified licenses: a large body of simple "
        "synthetic stories and a smaller slice of educational web text. The two "
        "differ in register, which gives a per-domain perplexity breakdown and "
        "separates what the models learn from each. No code data and no "
        "Wikipedia are included."
    )
    add("")
    add(
        "This file is generated by `scripts/05_write_data_doc.py` from "
        "`meta.json`, which is written by the tokenizer pass. Every count below "
        "comes from the corpus that was built."
    )
    add("")

    add("## Sources and licenses")
    add("")
    add(
        f"TinyStories ({ts_prov['url']}) is a corpus of short synthetic "
        "stories written with a small vocabulary, intended for training small "
        "language models that still produce fluent English. The license is "
        f"{ts_prov['license']} (Community Data License Agreement, Sharing, "
        "version 1.0). The dataset is not gated."
    )
    add("")
    add(
        f"FineWeb-Edu ({fw_prov['url']}) is web text filtered by an "
        "educational quality classifier, derived from Common Crawl. The license "
        f"is {fw_prov['license']} (Open Data Commons Attribution License "
        "version 1.0). The dataset is not gated."
    )
    add("")

    add("## Downloads")
    add("")
    add(
        "TinyStories is taken from the V2 GPT-4 variant specifically, the "
        "GPT-4-generated rewrite of the original GPT-3.5 corpus. The files are "
        + " and ".join(f"`{f}`" for f in ts_prov["files"])
        + ". They are plain text with documents separated by an `<|endoftext|>` "
        "marker line, and are fetched directly from the dataset repository "
        "because the V2 GPT-4 text is not exposed as a loadable dataset config. "
        f"Both files were pooled into a single document pool of {fmt(ts['documents_total'])} "
        f"documents and {fmt(ts['chars_raw'])} characters."
    )
    add("")
    add(
        f"FineWeb-Edu is streamed from the `{fw_prov['config']}` config and "
        "stopped early. The full 10BT sample is far larger than this study "
        "needs, so the "
        f"stream is cut once it reaches {fmt(fw_prov['char_target'])} characters, "
        f"yielding {fmt(fw['documents_total'])} documents and "
        f"{fmt(fw['chars_raw'])} characters. This is a prefix of the sample "
        "stream in dataset order, not a random sample of it. Documents in "
        "FineWeb-Edu are not ordered by any property that would bias a prefix, "
        "but a prefix is not a random draw, and the per-domain results carry "
        "that caveat."
    )
    add("")
    add(
        "Both domains are normalized to the same on-disk form before "
        "tokenization: JSON lines holding one document per line. Raw text and "
        "tokenized output live on external storage, not in this repository."
    )
    add("")

    add("## Tokenizer")
    add("")
    add(
        f"The tokenizer is a byte-level BPE with a vocabulary of "
        f"{fmt(tok['vocab_size'])}, trained on this mixture instead of borrowed "
        "from an existing model, so the vocabulary reflects the text the models "
        "see. Training used a sample drawn in proportion to the intended token "
        "mix, striding through each corpus so the sample spans the whole of each "
        "source. The full byte alphabet is included in the initial vocabulary, "
        "so any input round trips exactly, including characters the trainer "
        "never encountered."
    )
    add("")
    add(
        f"`{tok['eot_token']}` is the only special token and holds id "
        f"{tok['eot_id']}. It separates documents in the token streams. The "
        f"tokenizer is stored at `{tok['path']}` and is version controlled with "
        "the code, since reproducing any run requires the exact tokenizer. Its "
        f"SHA-256 is `{tok['sha256']}`."
    )
    add("")
    add(
        "Measured compression differs by domain:"
    )
    add("")
    add("| Domain | Characters | Tokens | Characters per token |")
    add("| --- | ---: | ---: | ---: |")
    for name, m in domains.items():
        add(
            f"| {DOMAIN_TITLES.get(name, name)} | {fmt(m['chars_raw'])} | "
            f"{fmt(total_tokens(m))} | {m['chars_per_token']:.2f} |"
        )
    add("")

    add("## Split protocol")
    add("")
    add(
        f"Splits are made by {proto['unit']}, never by cutting a token stream at "
        "an arbitrary position. If a flat stream of tokens were cut into train "
        "and validation pieces, a single story or web page could land on both "
        "sides of the cut, and held-out perplexity would then be partly "
        "measuring recall of text the model had already trained on."
    )
    add("")
    add(
        "Holdout documents are chosen and tokenized before the training stream "
        "is built. A seeded random draw marks a pool of candidate documents per "
        "domain. Those candidates fill validation to "
        f"about {millions(proto['val_tokens_target'])} tokens and then test to "
        f"about {millions(proto['test_tokens_target'])} tokens, counted in real "
        "tokens and not estimated from characters. Candidates left over once "
        "both are full are released back into training. Every remaining document "
        "is then streamed into the training file. A document belongs to exactly "
        "one split, and no text is shared "
        f"between training and evaluation. The draw is seeded with {proto['seed']} "
        "and is reproducible."
    )
    add("")
    add(
        "Within a split, windows may cross document boundaries. That is "
        "intended. Documents are joined by the separator token, and predicting "
        "the end of one document followed by the start of another is part of the "
        "modeling task. Because the split is by document, a window that spans a "
        "boundary inside the validation stream still contains only validation "
        "documents."
    )
    add("")

    add("## Token counts")
    add("")
    add(
        "Counts are exact, produced by the tokenizer pass and recorded in "
        "`meta.json`. Tokens are stored as unsigned 16 bit integers, which is "
        f"exact because the vocabulary of {fmt(tok['vocab_size'])} fits well "
        "inside the 65536 values a 16 bit integer holds."
    )
    add("")
    add("| Domain | Train | Validation | Test | Total |")
    add("| --- | ---: | ---: | ---: | ---: |")
    for name, m in domains.items():
        t = m["tokens"]
        add(
            f"| {DOMAIN_TITLES.get(name, name)} | {fmt(t['train'])} | "
            f"{fmt(t['val'])} | {fmt(t['test'])} | {fmt(total_tokens(m))} |"
        )
    add(
        f"| **Total** | **{fmt(train_total)}** | "
        f"**{fmt(sum(m['tokens']['val'] for m in domains.values()))}** | "
        f"**{fmt(sum(m['tokens']['test'] for m in domains.values()))}** | "
        f"**{fmt(grand_total)}** |"
    )
    add("")
    add(
        f"The corpus holds {fmt(grand_total)} tokens in total, of which "
        f"{fmt(train_total)} are available for training. By token count the "
        f"mixture is {ts_share:.1f} percent TinyStories and {fw_share:.1f} "
        "percent FineWeb-Edu. By document, "
        + " and ".join(
            f"{DOMAIN_TITLES.get(n, n)} contributes {fmt(m['documents_total'])} "
            f"documents of which {fmt(m['documents_holdout'])} are held out"
            for n, m in domains.items()
        )
        + "."
    )
    add("")
    add(
        "The training mixture ratio used by the loader is a training decision, "
        "not a property of the corpus. The loader samples each batch element's "
        "domain by configured weight, so the ratio seen during training is set "
        "there and does not have to match the ratio on disk."
    )
    add("")

    if ext is not None:
        ext_tokens = ext["tokens"]
        base_web_train = fw["tokens"]["train"]
        add("## Web extension")
        add("")
        add(
            "The base FineWeb-Edu train stream above holds "
            f"{fmt(base_web_train)} tokens. A run that draws 30 percent of a "
            "multi-billion-token budget from the web domain exhausts that in well "
            "under one pass, so the web side is extended by continuing the "
            "`sample-10BT` stream past the same document prefix and tokenizing the "
            "continuation into additional train-only shards."
        )
        add("")
        add(
            "The extension is not a straight continuation of the tokenizer pass. "
            "The registered 200-gram leakage check fired on it: `sample-10BT` "
            "contains near-duplicate documents of the held-out documents, and the "
            "original slice was clean only because holdout documents were excluded "
            "from exactly that prefix. The extension is therefore produced by "
            "`scripts/13_filter_ext.py`, which drops any extension document whose "
            "tokenized form shares a 200-token n-gram with the closed val or test "
            "stream. Measurements, including the pre-filter and post-filter gate "
            "results, are in `docs/DECONTAMINATION.md`."
        )
        add("")
        add("| Shard | Tokens |")
        add("| --- | ---: |")
        for shard in ext["shards"]:
            add(f"| `{shard['file']}` | {fmt(shard['tokens'])} |")
        add(f"| **Extension total** | **{fmt(ext_tokens)}** |")
        add("")
        add(
            f"With the extension the web train stream holds "
            f"{fmt(base_web_train + ext_tokens)} tokens. The extension is "
            "train-only: val, test and the split protocol above are untouched by "
            "it, and the base counts in the previous section are the counts the "
            "holdout evaluation uses."
        )
        add("")

    add("## Files")
    add("")
    add(f"Tokenized streams live in `{portable_path(TOKENIZED_ROOT)}`:")
    add("")
    add("| File | Size on disk |")
    add("| --- | ---: |")
    for name in domains:
        for split in ("train", "val", "test"):
            add(f"| `{name}_{split}.bin` | {bin_size(name, split)} |")
    if ext is not None:
        for shard in ext["shards"]:
            add(f"| `{shard['file']}` | {shard['bytes']/1e9:.2f} GB |")
    add("")
    add(
        "Each file is a flat array of unsigned 16 bit token ids with no header. "
        "`src/small_lm_lab/data.py` memory maps them directly."
    )
    add("")
    add("## Reproducing")
    add("")
    add(
        "Run the numbered scripts in order: `02_download.py` fetches the raw "
        "corpora, `03_train_tokenizer.py` trains the tokenizer, "
        "`04_tokenize.py` builds the token streams and writes `meta.json`, and "
        "`05_write_data_doc.py` regenerates this file. The download step is "
        "resumable and skips any domain already complete on disk."
    )
    add("")
    add(
        "The web extension is a separate pass: `02_download.py --extra-web-tokens "
        "2.5e9` fetches the continuation, `13_filter_ext.py` tokenizes and "
        "decontaminates it into the train-ext shards, and `12_leakage_check.py "
        "--domain fineweb_edu --extension` records the registered gate result. "
        "Neither corpus is redistributed here; both are fetched from their "
        "sources by these scripts."
    )
    add("")
    return "\n".join(lines)


def main() -> None:
    if not META_PATH.exists():
        raise FileNotFoundError(f"missing {META_PATH}; run scripts/04_tokenize.py first")
    with META_PATH.open() as f:
        meta = json.load(f)

    text = render(meta, load_extension_record())
    # Escapes rather than literals so this file stays free of the characters it
    # is checking for.
    if "\u2014" in text or "\u2013" in text:
        raise SystemExit("generated doc contains an em or en dash")

    DOC_PATH.parent.mkdir(parents=True, exist_ok=True)
    DOC_PATH.write_text(text, encoding="utf-8")
    print(f"Wrote {DOC_PATH} ({len(text):,} chars, {len(text.splitlines()):,} lines)")


if __name__ == "__main__":
    main()
